/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AdminTeachersIdImport } from './routes/_admin/teachers/$id'
import { Route as AdminStudentsIdImport } from './routes/_admin/students/$id'
import { Route as AdminEmployeesIdImport } from './routes/_admin/employees/$id'

// Create Virtual Routes

const AdminIndexLazyImport = createFileRoute('/_admin/')()
const AdminTeachersIndexLazyImport = createFileRoute('/_admin/teachers/')()
const AdminStudentsIndexLazyImport = createFileRoute('/_admin/students/')()
const AdminEmployeesIndexLazyImport = createFileRoute('/_admin/employees/')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexLazyRoute = AdminIndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_admin/index.lazy').then((d) => d.Route))

const AdminTeachersIndexLazyRoute = AdminTeachersIndexLazyImport.update({
  path: '/teachers/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_admin/teachers/index.lazy').then((d) => d.Route),
)

const AdminStudentsIndexLazyRoute = AdminStudentsIndexLazyImport.update({
  path: '/students/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_admin/students/index.lazy').then((d) => d.Route),
)

const AdminEmployeesIndexLazyRoute = AdminEmployeesIndexLazyImport.update({
  path: '/employees/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_admin/employees/index.lazy').then((d) => d.Route),
)

const AdminTeachersIdRoute = AdminTeachersIdImport.update({
  path: '/teachers/$id',
  getParentRoute: () => rootRoute,
} as any)

const AdminStudentsIdRoute = AdminStudentsIdImport.update({
  path: '/students/$id',
  getParentRoute: () => rootRoute,
} as any)

const AdminEmployeesIdRoute = AdminEmployeesIdImport.update({
  path: '/employees/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_admin/employees/$id': {
      id: '/_admin/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AdminEmployeesIdImport
      parentRoute: typeof rootRoute
    }
    '/_admin/students/$id': {
      id: '/_admin/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AdminStudentsIdImport
      parentRoute: typeof rootRoute
    }
    '/_admin/teachers/$id': {
      id: '/_admin/teachers/$id'
      path: '/teachers/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof AdminTeachersIdImport
      parentRoute: typeof rootRoute
    }
    '/_admin/employees/': {
      id: '/_admin/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AdminEmployeesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_admin/students/': {
      id: '/_admin/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AdminStudentsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_admin/teachers/': {
      id: '/_admin/teachers/'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AdminTeachersIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LoginRoute,
  AdminIndexLazyRoute,
  AdminEmployeesIdRoute,
  AdminStudentsIdRoute,
  AdminTeachersIdRoute,
  AdminEmployeesIndexLazyRoute,
  AdminStudentsIndexLazyRoute,
  AdminTeachersIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/login",
        "/_admin/",
        "/_admin/employees/$id",
        "/_admin/students/$id",
        "/_admin/teachers/$id",
        "/_admin/employees/",
        "/_admin/students/",
        "/_admin/teachers/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_admin/": {
      "filePath": "_admin/index.lazy.tsx"
    },
    "/_admin/employees/$id": {
      "filePath": "_admin/employees/$id.tsx"
    },
    "/_admin/students/$id": {
      "filePath": "_admin/students/$id.tsx"
    },
    "/_admin/teachers/$id": {
      "filePath": "_admin/teachers/$id.tsx"
    },
    "/_admin/employees/": {
      "filePath": "_admin/employees/index.lazy.tsx"
    },
    "/_admin/students/": {
      "filePath": "_admin/students/index.lazy.tsx"
    },
    "/_admin/teachers/": {
      "filePath": "_admin/teachers/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
